CODE_NAME_PRIVATBANK = 'CODE_NAME_PRIVATBANK'
CODE_NAME_MONOBANK = 'CODE_NAME_MONOBANK'
CODE_NAME_VKURSE = 'CODE_NAME_VKURSE'
CODE_NAME_ALFABANK = 'CODE_NAME_ALFABANK'
CODE_NAME_OSCHADBANK = 'CODE_NAME_OSCHADBANK'
CODE_NAME_UNIVERSALBANK = 'CODE_NAME_UNIVERSALBANK'

CACHE_KEY_LATEST_RATES = 'currency::views::LatestRateView::latest-rate'
