# Generated by Django 3.2.6 on 2021-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('path', models.CharField(max_length=255)),
                ('response_time', models.PositiveSmallIntegerField(help_text='in milliseconds.')),
                ('request_method', models.CharField(choices=[('get', 'GET'), ('post', 'POST')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='rate',
            name='type',
            field=models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro')], max_length=3),
        ),
    ]
